### ISSUE TITLE
gps intigration 

### ISSUE THREAD

**Issue by Aquahoodjd** [n1kdo/rotator-controller-controller#1]
what go you thing about a low cost gps multi format chip with a ceramic gap anttena or you ould add your own qhf helix (these rock by the way. You could orient your rotator of various design north to calibrate with gps, g predict, the messier catalog for astrophoto with a cam mount added?

**Comment by Aquahoodjd** [comment]
excuse the spelling

**Comment by n1kdo** [comment]
Hi,  this project controls an antenna rotator control box, not the rotator directly, so I am not sure your issue is applicable.  Thanks for looking, anyhow.  Jeff
